# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_reduce.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_reduce.proto',
  package='mapreduce',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10map_reduce.proto\x12\tmapreduce\x1a\x1bgoogle/protobuf/empty.proto\"X\n\tTaskInput\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.mapreduce.TaskType\x12\n\n\x02id\x18\x02 \x01(\r\x12\t\n\x01M\x18\x03 \x01(\r\x12\x11\n\tfilePaths\x18\x04 \x03(\t*9\n\x08TaskType\x12\x07\n\x03Map\x10\x00\x12\n\n\x06Reduce\x10\x01\x12\n\n\x06NoTask\x10\x02\x12\x0c\n\x08ShutDown\x10\x03\x32\xcf\x01\n\rDriverService\x12=\n\x0bRequestTask\x12\x16.google.protobuf.Empty\x1a\x14.mapreduce.TaskInput\"\x00\x12=\n\tFinishMap\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x0c\x46inishReduce\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])

_TASKTYPE = _descriptor.EnumDescriptor(
  name='TaskType',
  full_name='mapreduce.TaskType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Map', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Reduce', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoTask', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ShutDown', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=150,
  serialized_end=207,
)
_sym_db.RegisterEnumDescriptor(_TASKTYPE)

TaskType = enum_type_wrapper.EnumTypeWrapper(_TASKTYPE)
Map = 0
Reduce = 1
NoTask = 2
ShutDown = 3



_TASKINPUT = _descriptor.Descriptor(
  name='TaskInput',
  full_name='mapreduce.TaskInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mapreduce.TaskInput.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='mapreduce.TaskInput.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='M', full_name='mapreduce.TaskInput.M', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filePaths', full_name='mapreduce.TaskInput.filePaths', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=148,
)

_TASKINPUT.fields_by_name['type'].enum_type = _TASKTYPE
DESCRIPTOR.message_types_by_name['TaskInput'] = _TASKINPUT
DESCRIPTOR.enum_types_by_name['TaskType'] = _TASKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskInput = _reflection.GeneratedProtocolMessageType('TaskInput', (_message.Message,), dict(
  DESCRIPTOR = _TASKINPUT,
  __module__ = 'map_reduce_pb2'
  # @@protoc_insertion_point(class_scope:mapreduce.TaskInput)
  ))
_sym_db.RegisterMessage(TaskInput)



_DRIVERSERVICE = _descriptor.ServiceDescriptor(
  name='DriverService',
  full_name='mapreduce.DriverService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=210,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestTask',
    full_name='mapreduce.DriverService.RequestTask',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TASKINPUT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FinishMap',
    full_name='mapreduce.DriverService.FinishMap',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FinishReduce',
    full_name='mapreduce.DriverService.FinishReduce',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRIVERSERVICE)

DESCRIPTOR.services_by_name['DriverService'] = _DRIVERSERVICE

# @@protoc_insertion_point(module_scope)
