# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import map_reduce_pb2 as map__reduce__pb2


class DriverServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestTask = channel.unary_unary(
        '/mapreduce.DriverService/RequestTask',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=map__reduce__pb2.TaskInput.FromString,
        )
    self.FinishMap = channel.unary_unary(
        '/mapreduce.DriverService/FinishMap',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.FinishReduce = channel.unary_unary(
        '/mapreduce.DriverService/FinishReduce',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class DriverServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RequestTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinishMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FinishReduce(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestTask': grpc.unary_unary_rpc_method_handler(
          servicer.RequestTask,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=map__reduce__pb2.TaskInput.SerializeToString,
      ),
      'FinishMap': grpc.unary_unary_rpc_method_handler(
          servicer.FinishMap,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'FinishReduce': grpc.unary_unary_rpc_method_handler(
          servicer.FinishReduce,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mapreduce.DriverService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
