# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: map_reduce.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'map_reduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10map_reduce.proto\x12\tmapreduce\x1a\x1bgoogle/protobuf/empty.proto\"1\n\x05\x43hunk\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x04\"g\n\tTaskInput\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.mapreduce.TaskType\x12\n\n\x02id\x18\x02 \x01(\r\x12\t\n\x01M\x18\x03 \x01(\r\x12 \n\x06\x63hunks\x18\x04 \x03(\x0b\x32\x10.mapreduce.Chunk*9\n\x08TaskType\x12\x07\n\x03Map\x10\x00\x12\n\n\x06Reduce\x10\x01\x12\n\n\x06NoTask\x10\x02\x12\x0c\n\x08ShutDown\x10\x03\x32\xcf\x01\n\rDriverService\x12=\n\x0bRequestTask\x12\x16.google.protobuf.Empty\x1a\x14.mapreduce.TaskInput\"\x00\x12=\n\tFinishMap\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12@\n\x0c\x46inishReduce\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_reduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKTYPE']._serialized_start=216
  _globals['_TASKTYPE']._serialized_end=273
  _globals['_CHUNK']._serialized_start=60
  _globals['_CHUNK']._serialized_end=109
  _globals['_TASKINPUT']._serialized_start=111
  _globals['_TASKINPUT']._serialized_end=214
  _globals['_DRIVERSERVICE']._serialized_start=276
  _globals['_DRIVERSERVICE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
